source 'https://github.com/CocoaPods/Specs.git'

target 'SettingView', :exclusive => true do
  pod "SettingView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SettingView", :path => "../"

  
end
