source 'https://github.com/CocoaPods/Specs.git'

target 'App_Common', :exclusive => true do
  pod "App_Common", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "App_Common", :path => "../"

  
end
