source 'https://github.com/CocoaPods/Specs.git'

target 'NewsBase', :exclusive => true do
  pod "NewsBase", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NewsBase", :path => "../"

  
end
