source 'https://github.com/CocoaPods/Specs.git'

target 'TweetBase2', :exclusive => true do
  pod "TweetBase2", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TweetBase2", :path => "../"

  
end
