source 'https://github.com/CocoaPods/Specs.git'

target 'ProfileBase', :exclusive => true do
  pod "ProfileBase", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ProfileBase", :path => "../"

  
end
